name: Docker Build and Push

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Enter the name of the Environment to be deployed on'
        required: true
        type: string
        default: dev

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
              role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
              aws-region: us-east-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_REPO }}

      - name: Build, Tag, and Push Docker image to ECR
        id: containerImage
        run: |
          docker build -t my-image .
          docker tag my-image:latest ${{ secrets.AWS_ECR_REPO }}:latest
          docker push ${{ secrets.AWS_ECR_REPO }}:latest

      - name: ECR Status Check
        if: steps.containerImage.outcome == 'failure'
        run: exit 1
